### ISSUE TITLE
Extend Look and Feel

### ISSUE THREAD

**Issue by baumerik** [Microsoft/vsts-sample-wit-custom-control#6]
Nice Control, and I need it for different fields.
At the moment I use Picklists with string fields to do this. 

may be two things to extend:
1. give an option to render the list as dropdown (I my Case I have 3 of this fields with about 5-7 values nad so it takes a lot of space)
2. May be make the colors optional means not display a color if you do not fill in values

Thanks

Erik

**Comment by mmanela** [comment]
@baumerik Thanks for the feedback. 

For #1, since the extension run in an iframe we couldn't do a real dropdown that overlays other contents of the form but we could look into do a list that can expand/collapse and shift the form down by resizing the iframe? Would this work? We do this in our [Multivalue Control](https://github.com/Microsoft/vsts-extension-multivalue-control).

For #2, Currently as you see we default to our preset colors. What is the use case where you do not want any color given?

**Comment by cschleiden** [comment]
For #2 you should also be able to set the colors to transparent.

**Comment by baumerik** [comment]
@cschleiden 
For #2 transparent will work. It's just I'm am lazy to think about these colors and the defaults not really match ;-)

@mmanela 
and for #1 I have tried it and it will work.

regards
Erik

**Comment by baumerik** [comment]
@mmanela can you give me a timeframe when you will extend the control for #1?

Thx Erik

**Comment by mmanela** [comment]
@baumerik At this point I can't commit on a timeframe. I plan to have someone get to it but we have higher priorities at the moment. But we would gladly accept PR's if you want to get it sooner.

**Comment by shayki5** [comment]
Hi @mmanela :) do you know if you have a plan to do #1 ?

**Comment by MOlausson** [comment]
Sorry, but this code in this repo is not currently being maintained.
